# Generated by Django 4.2.7 on 2023-12-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoarticulos',
            name='usuariodatos_id',
        ),
        migrations.RemoveField(
            model_name='carritopedido',
            name='usuariodatos_id',
        ),
        migrations.RemoveField(
            model_name='historicalcarritoarticulos',
            name='usuariodatos_id',
        ),
        migrations.RemoveField(
            model_name='historicalcarritopedido',
            name='usuariodatos_id',
        ),
        migrations.AddField(
            model_name='carritoarticulos',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para los articulos'),
        ),
        migrations.AddField(
            model_name='carritopedido',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para el pedido'),
        ),
        migrations.AddField(
            model_name='historicalcarritoarticulos',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para los articulos'),
        ),
        migrations.AddField(
            model_name='historicalcarritopedido',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para el pedido'),
        ),
    ]
