# Generated by Django 4.2.7 on 2023-12-06 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_historicalproducto_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0002_remove_carritoarticulos_usuariodatos_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarritoArticulos',
            new_name='CarritoDetalle',
        ),
        migrations.RenameModel(
            old_name='HistoricalCarritoArticulos',
            new_name='HistoricalCarritoDetalle',
        ),
        migrations.AlterModelOptions(
            name='carritodetalle',
            options={'verbose_name': 'Detalle de carrito', 'verbose_name_plural': 'Detalles de Carrito'},
        ),
        migrations.AlterModelOptions(
            name='carritopedido',
            options={'verbose_name': 'Pedido de carrito', 'verbose_name_plural': 'Pedidos de carrito'},
        ),
        migrations.AlterModelOptions(
            name='historicalcarritodetalle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Detalle de carrito', 'verbose_name_plural': 'historical Detalles de Carrito'},
        ),
        migrations.AlterModelOptions(
            name='historicalcarritopedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pedido de carrito', 'verbose_name_plural': 'historical Pedidos de carrito'},
        ),
        migrations.RenameField(
            model_name='carritopedido',
            old_name='carrito_articulo_id',
            new_name='carrito_id',
        ),
        migrations.RenameField(
            model_name='historicalcarritopedido',
            old_name='carrito_articulo_id',
            new_name='carrito_id',
        ),
    ]
