# Generated by Django 4.2.7 on 2023-12-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_historicalproducto_nombre_and_more'),
        ('carrito', '0003_rename_carritoarticulos_carritodetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritodetalle',
            name='cupones_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.cuponesproducto', verbose_name='Cupon de articulos'),
        ),
    ]
