# Generated by Django 4.2.7 on 2023-12-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_carritodetalle_cupones_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcarritopedido',
            name='carrito_id',
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='total',
            field=models.TextField(max_length=12, null=True, verbose_name='Total de articulos'),
        ),
        migrations.RemoveField(
            model_name='carritopedido',
            name='carrito_id',
        ),
        migrations.AlterField(
            model_name='historicalcarritodetalle',
            name='total',
            field=models.TextField(max_length=12, null=True, verbose_name='Total de articulos'),
        ),
        migrations.AddField(
            model_name='carritopedido',
            name='carrito_id',
            field=models.ManyToManyField(related_name='pedidos', to='carrito.carritodetalle', verbose_name='Articulos pedido'),
        ),
    ]
