# Generated by Django 4.2.7 on 2023-12-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_historicalproducto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='color',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Color de producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='genero',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Genero de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=30, unique=True, verbose_name='Color de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(max_length=15, unique=True, verbose_name='Genero de producto'),
        ),
    ]
