# Generated by Django 4.2.7 on 2023-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_historicalproducto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponesproducto',
            name='descuento',
            field=models.TextField(max_length=10, verbose_name='Descuento de Cupon'),
        ),
        migrations.AlterField(
            model_name='historicalcuponesproducto',
            name='descuento',
            field=models.TextField(max_length=10, verbose_name='Descuento de Cupon'),
        ),
        migrations.AlterField(
            model_name='historicalofertasproducto',
            name='descuento',
            field=models.TextField(max_length=10, verbose_name='Descuento de oferta'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='precio',
            field=models.TextField(max_length=10, verbose_name='Precio de Producto'),
        ),
        migrations.AlterField(
            model_name='ofertasproducto',
            name='descuento',
            field=models.TextField(max_length=10, verbose_name='Descuento de oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.TextField(max_length=10, verbose_name='Precio de Producto'),
        ),
    ]
