# Generated by Django 4.2.7 on 2023-12-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_historicalusuariodatos_documento_and_more'),
        ('productos', '0004_alter_cuponesproducto_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuponesproducto',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='historicalcuponesproducto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='cuponesproducto',
            name='local_usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.localusuario', verbose_name='Local del usuario'),
        ),
        migrations.AddField(
            model_name='historicalcuponesproducto',
            name='local_usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.localusuario', verbose_name='Local del usuario'),
        ),
    ]
