# Generated by Django 4.2.7 on 2023-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_cuponesproducto_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Color de producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='genero',
            field=models.CharField(max_length=15, verbose_name='Genero de producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca de producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Color de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(max_length=15, verbose_name='Genero de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de producto'),
        ),
    ]
