# Generated by Django 4.2.7 on 2023-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_historicalproducto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de producto'),
        ),
    ]
