# Generated by Django 4.2.7 on 2023-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_historicalproducto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimagenesproducto',
            name='codigo',
            field=models.TextField(default=0, max_length=10, verbose_name='Codigo de imagen'),
        ),
        migrations.AddField(
            model_name='imagenesproducto',
            name='codigo',
            field=models.TextField(default=0, max_length=10, verbose_name='Codigo de imagen'),
        ),
    ]
