# Generated by Django 4.2.7 on 2023-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_historicalimagenesproducto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesproducto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='productos/', verbose_name='Imagen de producto'),
        ),
        migrations.DeleteModel(
            name='HistoricalImagenesProducto',
        ),
        migrations.DeleteModel(
            name='ImagenesProducto',
        ),
    ]
