# Generated by Django 4.2.7 on 2023-12-02 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrPeticion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha eliminacion')),
                ('descripcion', models.CharField(max_length=20, null=True, unique=True, verbose_name='Tipo de peticion')),
            ],
            options={
                'verbose_name': 'Tipo peticion pqr',
                'verbose_name_plural': 'Tipos peticiones pqrs',
            },
        ),
        migrations.RemoveField(
            model_name='historicalpqrinformacion',
            name='tipo_peticion',
        ),
        migrations.RemoveField(
            model_name='pqrinformacion',
            name='tipo_peticion',
        ),
        migrations.CreateModel(
            name='HistoricalPqrPeticion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_at', models.DateField(blank=True, editable=False, verbose_name='Fecha eliminacion')),
                ('descripcion', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Tipo de peticion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo peticion pqr',
                'verbose_name_plural': 'historical Tipos peticiones pqrs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalpqrinformacion',
            name='peticion_pqr_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.pqrpeticion', verbose_name='Tipo peticion pqr'),
        ),
        migrations.AddField(
            model_name='historicalpqrrespuesta',
            name='peticion_pqr_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.pqrpeticion', verbose_name='Tipo peticion pqr'),
        ),
        migrations.AddField(
            model_name='pqrinformacion',
            name='peticion_pqr_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pqrs.pqrpeticion', verbose_name='Tipo peticion pqr'),
        ),
        migrations.AddField(
            model_name='pqrrespuesta',
            name='peticion_pqr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pqrs.pqrpeticion', verbose_name='Tipo peticion pqr'),
        ),
    ]
