# Generated by Django 4.2.7 on 2023-12-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_pqrpeticion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpqrinformacion',
            name='num_radicado',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Número de Radicado'),
        ),
        migrations.AlterField(
            model_name='pqrinformacion',
            name='num_radicado',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de Radicado'),
        ),
    ]
