# Generated by Django 4.2.7 on 2023-12-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_historicalusuariodatos_documento_and_more'),
        ('pqrs', '0003_alter_historicalpqrinformacion_num_radicado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpqrrespuesta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pqr respuesta', 'verbose_name_plural': 'historical Pqrs respuesta'},
        ),
        migrations.AlterModelOptions(
            name='pqrrespuesta',
            options={'verbose_name': 'Pqr respuesta', 'verbose_name_plural': 'Pqrs respuesta'},
        ),
        migrations.AddField(
            model_name='historicalpqrrespuesta',
            name='local_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.localusuario', verbose_name='Local para la respuesta'),
        ),
        migrations.AddField(
            model_name='pqrrespuesta',
            name='local_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.localusuario', verbose_name='Local para la respuesta'),
        ),
    ]
