# Generated by Django 4.2.7 on 2023-12-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0007_remove_historicalpqrinformacion_archivos_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpqrpeticion',
            name='descripcion',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo de peticion'),
        ),
        migrations.AlterField(
            model_name='pqrpeticion',
            name='descripcion',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo de peticion'),
        ),
    ]
