# Generated by Django 4.2.7 on 2023-12-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0008_alter_historicalpqrpeticion_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpqrinformacion',
            old_name='usuariodatos_id',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='pqrinformacion',
            old_name='usuariodatos_id',
            new_name='usuario_id',
        ),
    ]
