# Generated by Django 4.2.7 on 2023-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historicalusuario_name_usuario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
    ]
