# Generated by Django 4.2.7 on 2023-12-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_historicalusuario_last_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuariodatos',
            name='documento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuariodatos',
            name='documento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.usuario', verbose_name='Seleccionar usuario'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locales_usuarios', to='usuarios.usuario', verbose_name='Seleccionar usuario'),
        ),
    ]
