# Generated by Django 4.2.7 on 2023-12-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_historicalusuariodatos_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocalusuario',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='localusuario',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='locales_usuarios',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.localusuario', verbose_name='Local para usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locales_usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.localusuario', verbose_name='Local para usuario'),
        ),
    ]
