# Generated by Django 4.2.7 on 2023-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_historicallocalusuario_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='direccion_local',
            field=models.CharField(max_length=50, verbose_name='Direccion local'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='nit_local',
            field=models.CharField(max_length=9, verbose_name='Nit local'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='nombre_local',
            field=models.CharField(max_length=40, verbose_name='Nombre local'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='telefono_local',
            field=models.CharField(max_length=10, verbose_name='Telefono local'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='direccion_local',
            field=models.CharField(max_length=50, verbose_name='Direccion local'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='nit_local',
            field=models.CharField(max_length=9, verbose_name='Nit local'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='nombre_local',
            field=models.CharField(max_length=40, verbose_name='Nombre local'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='telefono_local',
            field=models.CharField(max_length=10, verbose_name='Telefono local'),
        ),
    ]
