# Generated by Django 4.2.7 on 2023-12-04 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_historicallocalusuario_direccion_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='locales_usuarios',
        ),
        migrations.RemoveField(
            model_name='historicalusuariodatos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='locales_usuarios',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='documento',
        ),
        migrations.AddField(
            model_name='historicallocalusuario',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Datos de usuario'),
        ),
        migrations.AddField(
            model_name='localusuario',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locales_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Datos de usuario'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='direccion_local',
            field=models.CharField(max_length=50, verbose_name='Direccion usuario'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='nit_local',
            field=models.CharField(max_length=9, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='nombre_local',
            field=models.CharField(max_length=40, verbose_name='Nombre usuario'),
        ),
        migrations.AlterField(
            model_name='historicallocalusuario',
            name='telefono_local',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='direccion_local',
            field=models.CharField(max_length=50, verbose_name='Direccion usuario'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='nit_local',
            field=models.CharField(max_length=9, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='nombre_local',
            field=models.CharField(max_length=40, verbose_name='Nombre usuario'),
        ),
        migrations.AlterField(
            model_name='localusuario',
            name='telefono_local',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
