# Generated by Django 4.2.7 on 2023-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carritoarticulos_usuariodatos_id_and_more'),
        ('pqrs', '0006_remove_historicalpqrrespuesta_usuariodatos_id_and_more'),
        ('usuarios', '0008_remove_historicallocalusuario_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='usuariodatos_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuariodatos_id',
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion usuario'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='documento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='telefono',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono usuario'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='tipo_documento',
            field=models.CharField(default='', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(default='', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='usuarios/', verbose_name='Imagen de perfil'),
        ),
        migrations.DeleteModel(
            name='HistoricalUsuarioDatos',
        ),
        migrations.DeleteModel(
            name='UsuarioDatos',
        ),
    ]
