# Generated by Django 4.2.7 on 2023-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_historicalusuario_usuariodatos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
        migrations.AddField(
            model_name='historicallocalusuario',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de local'),
        ),
        migrations.AddField(
            model_name='localusuario',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='locales/', verbose_name='Imagen de local'),
        ),
    ]
