# Generated by Django 4.2.7 on 2023-12-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_historicalusuario_image_remove_usuario_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='locales_usuarios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='locales_usuarios',
        ),
        migrations.AddField(
            model_name='historicallocalusuario',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para la peticion'),
        ),
        migrations.AddField(
            model_name='localusuario',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario para la peticion'),
        ),
    ]
