# Generated by Django 4.2.7 on 2023-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_historicallocalusuario_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios_roles', related_query_name='usuario', to='usuarios.roles', verbose_name='Roles del usuario'),
        ),
    ]
