# Generated by Django 4.2.7 on 2023-12-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroles',
            name='nombre_rol',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Nombre rol'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nombre rol'),
        ),
    ]
