# Generated by Django 4.2.7 on 2023-12-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_historicalroles_nombre_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='roles_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles_id',
        ),
    ]
