# Generated by Django 4.2.7 on 2023-12-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_historicalusuario_roles_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='roles_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.roles', verbose_name='Rol de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.roles', verbose_name='Rol de usuario'),
        ),
    ]
